name: PicoArgs compile and test

on:
  push:
    branches: [ "dotnet8" ]

  pull_request:
    branches: [ "dotnet8" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - name: Test
      run: dotnet test --no-restore
